name-template: "Web v$RESOLVED_VERSION"
tag-template: "web-v$RESOLVED_VERSION"
tag-prefix: "web-v"
filter-by-labels: true
include-labels: ["App: Web"]
version-resolver:
  major:
    labels:
      - "BREAKING"
      - "Bump: Major"
  minor:
    labels:
      - "Type: Feature"
      - "Bump: Minor"
  patch:
    labels:
      - "Type: Bug"
      - "Type: Maintenance"
      - "Bump: Patch"
  default: patch
categories:
  - title: "🚀 New"
    labels: ["Type: Feature"]
  - title: "🐞 Fixes"
    labels: ["Type: Bug"]
  - title: "🧹 Maintenance"
    labels: ["Type: Maintenance"]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
