name: Manual Version Print

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Optional prefix for version"
        required: false
        default: "server-v"

jobs:
  print-version:
    name: Print Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
          prefix: ${{ github.event.inputs.prefix }}

      - name: Print Version
        run: echo "Version is ${{ steps.get_version.outputs.version }}"
