name: Release Version Print

on:
  release:
    types: [published]

jobs:
  print-version:
    name: Print Version for Release
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'server-v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
          prefix: "server-v"

      - name: Print Version
        run: echo "Version is ${{ steps.get_version.outputs.version }}"
