name: Tag Version Print

on:
  push:
    tags:
      - "server-v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Specific server tag to build (e.g., server-v2.3.4)"
        required: false
        type: string

jobs:
  print-server-version:
    name: Print Server Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate tag input
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/validate-tag
        with:
          tag: ${{ github.event.inputs.tag }}
          prefix: "server-v"

      - name: Checkout specific tag
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
          prefix: "server-v"

      - name: Print Version
        run: echo "Server Version is ${{ steps.get_version.outputs.version }}"
